export const productDetails = [
    {
        id: 1,
        name: "Boat 1",
        rating: 4,
        price: 899,
        reviews: 344,
        image: "/assets/earphones_a_1.webp",
        category: "earphone",
    },
    {
        id: 2,
        name: "Boat 2",
        rating: 4.5,
        price: 950,
        reviews: 3990,
        image: "/assets/earphones_b_1.webp",
        category: "earphone",
    },
    {
        id: 3,
        name: "Boat 3",
        rating: 3,
        price: 1500,
        reviews: 100,
        image: "/assets/earphones_b_3.webp",
        category: "earphone",
    },
    {
        id: 4,
        name: "Boat 4",
        rating: 3.5,
        price: 1999,
        reviews: 10,
        image: "/assets/earphones_c_1.webp",
        category: "earphone",
    },

    {
        id: 7,
        name: "Headphone 1",
        rating: 3,
        price: 2000,
        reviews: 100,
        image: "/assets/headphones_a_1.webp",
        category: "headphone",
    },
    {
        id: 8,
        name: "Headphone 2",
        rating: 5,
        price: 2999,
        reviews: 20000,
        image: "/assets/headphones_b_1.webp",
        category: "headphone",
    },
    {
        id: 9,
        name: "Headphone 3",
        rating: 4.5,
        price: 2399,
        reviews: 9200,
        image: "/assets/headphones_a_2.webp",
        category: "headphone",
    },
    {
        id: 10,
        name: "Headphone 4",
        rating: 4,
        price: 9000,
        reviews: 5666,
        image: "/assets/headphones_c_1.webp",
        category: "headphone",
    },
    {
        id: 11,
        name: "Speaker 1",
        rating: 3,
        price: 9000,
        reviews: 10088,
        image: "/assets/speaker1.webp",
        category: "speaker",
    },
    {
        id: 12,
        name: "Speaker 2",
        rating: 2,
        price: 9000,
        reviews: 8,
        image: "/assets/speaker2.webp",
        category: "speaker",
    },
    {
        id: 13,
        name: "Speaker 3",
        rating: 2.5,
        price: 45,
        reviews: 10000,
        image: "/assets/speaker3.webp",
        category: "speaker",
    },
    {
        id: 14,
        name: "Speaker 4",
        rating: 5,
        price: 5999,
        reviews: 10000,
        image: "/assets/speaker4.webp",
        category: "speaker",
    },
    {
        id: 15,
        name: "Watch 1",
        rating: 3.5,
        price: 1000,
        reviews: 106,
        image: "/assets/watch_1.webp",
        category: "watch",
    },
    {
        id: 16,
        name: "Watch 2",
        rating: 5,
        price: 9000,
        reviews: 14555,
        image: "/assets/watch_2.webp",
        category: "watch",
    },
    {
        id: 17,
        name: "Watch 3",
        rating: 5,
        price: 999,
        reviews: 78889,
        image: "/assets/watch_3.webp",
        category: "watch",
    },
    {
        id: 18,
        name: "Watch 4",
        rating: 4,
        price: 899,
        reviews: 4555,
        image: "/assets/watch_4.webp",
        category: "watch",
    },
];
